pool:
  vmImage: "Ubuntu 16.04"

variables:
  GOBIN: $(GOPATH)/bin
  GOPATH: $(system.defaultWorkingDirectory)/gopath
  GOROOT: /usr/local/go1.11
  modulePath: $(GOPATH)/src/dev.azure.com/rchi-texas/$(build.repository.name)

steps:
  - script: |
      mkdir -p '$(GOBIN)'
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      mv !(gopath) '$(modulePath)'
      echo '##vso[task.prependpath]$(GOBIN)'
      echo '##vso[task.prependpath]$(GOROOT)/bin'
    displayName: "Set up the Go workspace"

  - script: |
      go get -v -t -d ./...
      go build -v .
      go get github.com/tebeka/go2xunit
      2>&1 go test -v ./... | go2xunit -output tests.xml
    workingDirectory: $(modulePath)
    displayName: "Get dependencies and run tests"

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'xUnit' # Options: JUnit, NUnit, VSTest, xUnit
    testResultsFiles: '**/tests.xml' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: false # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional